<a href="https://colab.research.google.com/github/vishaldubey21/Facial-Expression-Recognition-CK-/blob/master/EmotionRecognitionColab.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [0]:
from google.colab import drive
drive.mount('/content/drive')

Go to this URL in a browser: https://accounts.google.com/o/oauth2/auth?client_id=947318989803-6bn6qk8qdgf4n4g3pfee6491hc0brc4i.apps.googleusercontent.com&redirect_uri=urn%3Aietf%3Awg%3Aoauth%3A2.0%3Aoob&scope=email%20https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fdocs.test%20https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fdrive%20https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fdrive.photos.readonly%20https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fpeopleapi.readonly&response_type=code

Enter your authorization code:
··········
Mounted at /content/drive


In [0]:
!ls "/content/drive/My Drive/Dataset/Emotion/cohn-kanade-images"

S005  S035  S054  S064	S074  S084  S094  S104	S114  S125  S135  S155	S506
S010  S037  S055  S065	S075  S085  S095  S105	S115  S126  S136  S156	S895
S011  S042  S056  S066	S076  S086  S096  S106	S116  S127  S137  S157	S999
S014  S044  S057  S067	S077  S087  S097  S107	S117  S128  S138  S158
S022  S045  S058  S068	S078  S088  S098  S108	S118  S129  S139  S160
S026  S046  S059  S069	S079  S089  S099  S109	S119  S130  S147  S501
S028  S050  S060  S070	S080  S090  S100  S110	S120  S131  S148  S502
S029  S051  S061  S071	S081  S091  S101  S111	S121  S132  S149  S503
S032  S052  S062  S072	S082  S092  S102  S112	S122  S133  S151  S504
S034  S053  S063  S073	S083  S093  S103  S113	S124  S134  S154  S505


In [0]:
import tensorflow as tf
import sklearn
import sklearn.linear_model
import sklearn.datasets
import matplotlib.pyplot as plt
import sklearn.ensemble
import pickle
import pylab as pl
import scipy.misc as smp
import pandas as pd
import numpy as np
import os
from PIL import Image
import math
import imghdr
import cv2
from sklearn.utils import shuffle
from sklearn.model_selection import train_test_split
from keras.models import Sequential
from keras.layers import Dense, Activation,Flatten,Dropout
from functools import partial
from operator import is_not
from keras.preprocessing.image import img_to_array,load_img
from PIL import Image



Using TensorFlow backend.


In [0]:
def labelsandimages(root_dir):
    file_dir = {}
    parent_folder = [os.path.join(root_dir,f) for f in os.listdir(root_dir)]
    for subfolder in parent_folder:
      folders = [os.path.join(subfolder,f) for f in os.listdir(subfolder)]
        
      for subfolder1 in folders:
        if(not os.path.isdir(subfolder1)):
          continue
        filecontainer = [os.path.join(subfolder1,f) for f in os.listdir(subfolder1)]
        filecontainer.sort()
        
        for file in filecontainer:
              parent_key = file.split('/')[-3] + file.split('/')[-2]
              if(parent_key not in file_dir):
                file_dir[parent_key]={}
              if(file.endswith(".txt")):
                file_dir[parent_key]['text_file'] = file
              elif(file.endswith(".png")):
                if('image' not in file_dir[parent_key]):
                  file_dir[parent_key]['image'] = []              
                file_dir[parent_key]['image'].append(file)
            
    return file_dir
            

In [0]:
image_and_label = labelsandimages("/content/drive/My Drive/Dataset/Emotion/cohn-kanade-images")

In [0]:
#image_and_label

In [0]:
image=np.zeros((1635,200,200,3),dtype = object)
label=np.zeros((1635,),dtype=int)

      

    


    

In [0]:
count_y=0
count_x=0
for d_id,value in image_and_label.items():
  for key in value:
    if('text_file' in key):
      f = open(value['text_file'],"rb")
      y = int(float(f.readline()))
      for i in range(4):
        label[count_y] =y
        count_y+=1
      img = cv2.imread(value['image'][-1])
      img = cv2.resize(img,(200,200),3)
      image[count_x]=img
      count_x+=1
      img = cv2.imread(value['image'][-2])
      img = cv2.resize(img,(200,200),3)
      image[count_x]=img
      count_x+=1
      img = cv2.imread(value['image'][-3])
      img = cv2.resize(img,(200,200),3)
      image[count_x]=img
      count_x+=1
      img = cv2.imread(value['image'][-4])
      img = cv2.resize(img,(200,200),3)
      image[count_x]=img
      count_x+=1
      label[count_y] = 0
      count_y+=1
      img = cv2.imread(value['image'][0])
      img = cv2.resize(img,(200,200),3)
      image[count_x]=img
      count_x+=1

In [0]:
labels = label.reshape(-1,1)
from sklearn.preprocessing import OneHotEncoder
onehotencoder = OneHotEncoder(categorical_features =[0])
labels = onehotencoder.fit_transform(labels).toarray()

/usr/local/lib/python3.6/dist-packages/sklearn/preprocessing/_encoders.py:415: FutureWarning: The handling of integer data will change in version 0.22. Currently, the categories are determined based on the range [0, max(values)], while in the future they will be determined based on the unique values.
If you want the future behaviour and silence this warning, you can specify "categories='auto'".
In case you used a LabelEncoder before this OneHotEncoder to convert the categories to integers, then you can now use the OneHotEncoder directly.
  warnings.warn(msg, FutureWarning)
/usr/local/lib/python3.6/dist-packages/sklearn/preprocessing/_encoders.py:451: DeprecationWarning: The 'categorical_features' keyword is deprecated in version 0.20 and will be removed in 0.22. You can use the ColumnTransformer instead.
  "use the ColumnTransformer instead.", DeprecationWarning)


In [0]:
labels.shape
for i in range(10):
    print(labels[i])

[0. 1. 0. 0. 0. 0. 0. 0.]
[0. 1. 0. 0. 0. 0. 0. 0.]
[0. 1. 0. 0. 0. 0. 0. 0.]
[0. 1. 0. 0. 0. 0. 0. 0.]
[1. 0. 0. 0. 0. 0. 0. 0.]
[0. 0. 0. 0. 1. 0. 0. 0.]
[0. 0. 0. 0. 1. 0. 0. 0.]
[0. 0. 0. 0. 1. 0. 0. 0.]
[0. 0. 0. 0. 1. 0. 0. 0.]
[1. 0. 0. 0. 0. 0. 0. 0.]


In [0]:
image , labels = shuffle(image,labels)
x_train,x_test,y_train,y_test = train_test_split(image,labels,test_size=0.2) 

In [0]:
from keras.applications import resnet50

In [0]:
base_model = resnet50.ResNet50(
    weights = 'imagenet', include_top=False, input_shape=(200,200, 3))

W0712 09:13:44.749362 140015271847808 deprecation_wrapper.py:119] From /usr/local/lib/python3.6/dist-packages/keras/backend/tensorflow_backend.py:74: The name tf.get_default_graph is deprecated. Please use tf.compat.v1.get_default_graph instead.

W0712 09:13:44.792742 140015271847808 deprecation_wrapper.py:119] From /usr/local/lib/python3.6/dist-packages/keras/backend/tensorflow_backend.py:517: The name tf.placeholder is deprecated. Please use tf.compat.v1.placeholder instead.

W0712 09:13:44.818534 140015271847808 deprecation_wrapper.py:119] From /usr/local/lib/python3.6/dist-packages/keras/backend/tensorflow_backend.py:4185: The name tf.truncated_normal is deprecated. Please use tf.random.truncated_normal instead.

W0712 09:13:44.873068 140015271847808 deprecation_wrapper.py:119] From /usr/local/lib/python3.6/dist-packages/keras/backend/tensorflow_backend.py:174: The name tf.get_default_session is deprecated. Please use tf.compat.v1.get_default_session instead.

W0712 09:13:44.874189

94658560/94653016 [==============================] - 1s 0us/step


In [0]:
for layer in base_model.layers[:-4]:
    layer.trainable = False

In [0]:
for layer in base_model.layers:
    print(layer, layer.trainable)
base_model.summary()

<keras.engine.input_layer.InputLayer object at 0x7f578c422208> False
<keras.layers.convolutional.ZeroPadding2D object at 0x7f578c220128> False
<keras.layers.convolutional.Conv2D object at 0x7f57cb3e2cc0> False
<keras.layers.normalization.BatchNormalization object at 0x7f578c264940> False
<keras.layers.core.Activation object at 0x7f578c264ac8> False
<keras.layers.convolutional.ZeroPadding2D object at 0x7f578ba014a8> False
<keras.layers.pooling.MaxPooling2D object at 0x7f578b9e40f0> False
<keras.layers.convolutional.Conv2D object at 0x7f578c220dd8> False
<keras.layers.normalization.BatchNormalization object at 0x7f578713bf28> False
<keras.layers.core.Activation object at 0x7f578713be80> False
<keras.layers.convolutional.Conv2D object at 0x7f57870ae978> False
<keras.layers.normalization.BatchNormalization object at 0x7f578708d550> False
<keras.layers.core.Activation object at 0x7f578704f748> False
<keras.layers.convolutional.Conv2D object at 0x7f5786f94e48> False
<keras.layers.convolution

In [0]:
model = Sequential()
model.add(base_model)
model.add(Flatten())
model.add(Dense(512, activation='relu'))
model.add(Dropout(0.6))
model.add(Dense(200, activation='relu'))
model.add(Dropout(0.5))
model.add(Dense(8, activation='softmax'))

W0712 09:14:01.681838 140015271847808 deprecation.py:506] From /usr/local/lib/python3.6/dist-packages/keras/backend/tensorflow_backend.py:3445: calling dropout (from tensorflow.python.ops.nn_ops) with keep_prob is deprecated and will be removed in a future version.
Instructions for updating:
Please use `rate` instead of `keep_prob`. Rate should be set to `rate = 1 - keep_prob`.
W0712 09:14:01.683037 140015271847808 nn_ops.py:4224] Large dropout rate: 0.6 (>0.5). In TensorFlow 2.x, dropout() uses dropout rate instead of keep_prob. Please ensure that this is intended.


In [0]:
model.summary()

_________________________________________________________________
Layer (type)                 Output Shape              Param #   
resnet50 (Model)             (None, 7, 7, 2048)        23587712  
_________________________________________________________________
flatten_1 (Flatten)          (None, 100352)            0         
_________________________________________________________________
dense_1 (Dense)              (None, 512)               51380736  
_________________________________________________________________
dropout_1 (Dropout)          (None, 512)               0         
_________________________________________________________________
dense_2 (Dense)              (None, 200)               102600    
_________________________________________________________________
dropout_2 (Dropout)          (None, 200)               0         
_________________________________________________________________
dense_3 (Dense)              (None, 8)                 1608      
Total para

In [0]:
model.compile(loss='categorical_crossentropy',
              optimizer='rmsprop',
              metrics=['acc'])
history = model.fit(x_train,y_train,epochs=100,
                   validation_data=(x_test,y_test),
                   verbose = 1)

W0712 09:14:01.776696 140015271847808 deprecation_wrapper.py:119] From /usr/local/lib/python3.6/dist-packages/keras/optimizers.py:790: The name tf.train.Optimizer is deprecated. Please use tf.compat.v1.train.Optimizer instead.

W0712 09:14:01.920996 140015271847808 deprecation.py:323] From /usr/local/lib/python3.6/dist-packages/tensorflow/python/ops/math_grad.py:1250: add_dispatch_support.<locals>.wrapper (from tensorflow.python.ops.array_ops) is deprecated and will be removed in a future version.
Instructions for updating:
Use tf.where in 2.0, which has the same broadcast rule as np.where


Train on 1308 samples, validate on 327 samples
Epoch 1/100
1308/1308 [==============================] - 385s 294ms/step - loss: 12.8760 - acc: 0.1827 - val_loss: 13.7534 - val_acc: 0.1468
Epoch 2/100
1308/1308 [==============================] - 379s 290ms/step - loss: 11.9929 - acc: 0.2508 - val_loss: 12.8952 - val_acc: 0.1988
Epoch 3/100
1308/1308 [==============================] - 380s 291ms/step - loss: 12.4412 - acc: 0.2271 - val_loss: 13.2099 - val_acc: 0.1804
Epoch 4/100
1308/1308 [==============================] - 381s 292ms/step - loss: 11.6989 - acc: 0.2676 - val_loss: 11.6262 - val_acc: 0.2722
Epoch 5/100
1308/1308 [==============================] - 380s 291ms/step - loss: 11.3711 - acc: 0.2898 - val_loss: 13.2099 - val_acc: 0.1804
Epoch 6/100
1308/1308 [==============================] - 379s 290ms/step - loss: 11.5693 - acc: 0.2775 - val_loss: 12.5199 - val_acc: 0.2232
Epoch 7/100
1308/1308 [==============================] - 378s 289ms/step - loss: 10.8311 - acc: 0.3249 - va

In [0]:
"""Let's test our model with more generated data"""
cross_loss, cross_acc = model.evaluate(x_test,y_test)
train_loss, train_acc = model.evaluate(x_train,y_train)
predictions = np.argmax(model.predict(x_train),axis=1)
print("Train Accuracy",train_acc)
print("Cross Validation Accuracy",cross_acc)

In [0]:
plt.figure(figsize=[8,6])
plt.plot(history.history['loss'],'r',linewidth=3.0)
plt.plot(history.history['val_loss'],'b',linewidth=3.0)
plt.legend(['Training loss', 'Validation Loss'],fontsize=18)
plt.xlabel('Epochs ',fontsize=16)
plt.ylabel('Loss',fontsize=16)
plt.title('Loss Curves',fontsize=16)
 
# Accuracy Curves
plt.figure(figsize=[8,6])
plt.plot(history.history['acc'],'r',linewidth=3.0)
plt.plot(history.history['val_acc'],'b',linewidth=3.0)
plt.legend(['Training Accuracy', 'Validation Accuracy'],fontsize=18)
plt.xlabel('Epochs ',fontsize=16)
plt.ylabel('Accuracy',fontsize=16)
plt.title('Accuracy Curves',fontsize=16)
plt.savefig("AccuracyErrorCurveResnet.png")